name: Executar Script Python

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libgit2-dev python3-dev

      - name: Instalar dependências do Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          python main.py
